/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as agentAttachments from "../agentAttachments.js";
import type * as agentOps from "../agentOps.js";
import type * as agentOpsReadModels from "../agentOpsReadModels.js";
import type * as agentTelemetry from "../agentTelemetry.js";
import type * as agentThreadContext from "../agentThreadContext.js";
import type * as agents_index from "../agents/index.js";
import type * as agents_internal from "../agents/internal.js";
import type * as agents_outreach_context from "../agents/outreach/context.js";
import type * as agents_outreach_index from "../agents/outreach/index.js";
import type * as agents_outreach_rag from "../agents/outreach/rag.js";
import type * as agents_outreach_tools_approveSocialActionRequest from "../agents/outreach/tools/approveSocialActionRequest.js";
import type * as agents_outreach_tools_approveTask from "../agents/outreach/tools/approveTask.js";
import type * as agents_outreach_tools_askHuman from "../agents/outreach/tools/askHuman.js";
import type * as agents_outreach_tools_attachmentReferences from "../agents/outreach/tools/attachmentReferences.js";
import type * as agents_outreach_tools_displayEntity from "../agents/outreach/tools/displayEntity.js";
import type * as agents_outreach_tools_generatePlan from "../agents/outreach/tools/generatePlan.js";
import type * as agents_outreach_tools_getProspectInteractionHistory from "../agents/outreach/tools/getProspectInteractionHistory.js";
import type * as agents_outreach_tools_getProspectPlan from "../agents/outreach/tools/getProspectPlan.js";
import type * as agents_outreach_tools_getSocialContext from "../agents/outreach/tools/getSocialContext.js";
import type * as agents_outreach_tools_helpers from "../agents/outreach/tools/helpers.js";
import type * as agents_outreach_tools_index from "../agents/outreach/tools/index.js";
import type * as agents_outreach_tools_inspectWorkspace from "../agents/outreach/tools/inspectWorkspace.js";
import type * as agents_outreach_tools_planLifecycle from "../agents/outreach/tools/planLifecycle.js";
import type * as agents_outreach_tools_refinePlan from "../agents/outreach/tools/refinePlan.js";
import type * as agents_outreach_tools_researchProspect from "../agents/outreach/tools/researchProspect.js";
import type * as agents_outreach_tools_socialAction from "../agents/outreach/tools/socialAction.js";
import type * as agents_outreach_tools_socialContextShared from "../agents/outreach/tools/socialContextShared.js";
import type * as agents_outreach_tools_xPostLimitHelpers from "../agents/outreach/tools/xPostLimitHelpers.js";
import type * as agents_prompts from "../agents/prompts.js";
import type * as agents_tools_analyzeUrl from "../agents/tools/analyzeUrl.js";
import type * as agents_tools_convertToSocialQueries from "../agents/tools/convertToSocialQueries.js";
import type * as agents_tools_createWorkspace from "../agents/tools/createWorkspace.js";
import type * as agents_tools_enrichProspect from "../agents/tools/enrichProspect.js";
import type * as agents_tools_generateImprovedDescription from "../agents/tools/generateImprovedDescription.js";
import type * as agents_tools_getUserStatus from "../agents/tools/getUserStatus.js";
import type * as agents_tools_index from "../agents/tools/index.js";
import type * as agents_tools_logging from "../agents/tools/logging.js";
import type * as agents_tools_planBatch from "../agents/tools/planBatch.js";
import type * as agents_tools_qualifyProspect from "../agents/tools/qualifyProspect.js";
import type * as agents_tools_queryWorkspace from "../agents/tools/queryWorkspace.js";
import type * as agents_tools_rememberWorkspaceMemory from "../agents/tools/rememberWorkspaceMemory.js";
import type * as agents_tools_schemas from "../agents/tools/schemas.js";
import type * as agents_tools_searchProspects from "../agents/tools/searchProspects.js";
import type * as agents_tools_searchWorkspaceMemories from "../agents/tools/searchWorkspaceMemories.js";
import type * as agents_tools_updateWorkspace from "../agents/tools/updateWorkspace.js";
import type * as agents_tools_workspaceMemoryHelpers from "../agents/tools/workspaceMemoryHelpers.js";
import type * as agents_tools_workspaceSetupContext from "../agents/tools/workspaceSetupContext.js";
import type * as analytics from "../analytics.js";
import type * as archivedProspectPause from "../archivedProspectPause.js";
import type * as autoPlanActions from "../autoPlanActions.js";
import type * as autoPlanGroundingCache from "../autoPlanGroundingCache.js";
import type * as autoPlanRuns from "../autoPlanRuns.js";
import type * as autocomplete from "../autocomplete.js";
import type * as autocompleteControl from "../autocompleteControl.js";
import type * as billing from "../billing.js";
import type * as chat from "../chat.js";
import type * as crons from "../crons.js";
import type * as discoveryEdges from "../discoveryEdges.js";
import type * as evaluator from "../evaluator.js";
import type * as exaApiBudget from "../exaApiBudget.js";
import type * as http from "../http.js";
import type * as integrations_bishopi from "../integrations/bishopi.js";
import type * as integrations_linkedin_getCompany from "../integrations/linkedin/getCompany.js";
import type * as integrations_linkedin_getPostComments from "../integrations/linkedin/getPostComments.js";
import type * as integrations_linkedin_getProfile from "../integrations/linkedin/getProfile.js";
import type * as integrations_linkedin_getProfilePosts from "../integrations/linkedin/getProfilePosts.js";
import type * as integrations_linkedin_linkdapiClient from "../integrations/linkedin/linkdapiClient.js";
import type * as integrations_linkedin_profileIdentity from "../integrations/linkedin/profileIdentity.js";
import type * as integrations_linkedin_searchPeople from "../integrations/linkedin/searchPeople.js";
import type * as integrations_linkedin_searchPosts from "../integrations/linkedin/searchPosts.js";
import type * as integrations_linkedin_searchUserPosts from "../integrations/linkedin/searchUserPosts.js";
import type * as integrations_twitter_getProfile from "../integrations/twitter/getProfile.js";
import type * as integrations_twitter_getThread from "../integrations/twitter/getThread.js";
import type * as integrations_twitter_searchPosts from "../integrations/twitter/searchPosts.js";
import type * as integrations_twitter_searchUserPosts from "../integrations/twitter/searchUserPosts.js";
import type * as integrations_twitter_similarProfiles from "../integrations/twitter/similarProfiles.js";
import type * as interactions from "../interactions.js";
import type * as interactionsActions from "../interactionsActions.js";
import type * as keywords from "../keywords.js";
import type * as lib_accessHelpers from "../lib/accessHelpers.js";
import type * as lib_agentAttachmentReferenceCore from "../lib/agentAttachmentReferenceCore.js";
import type * as lib_agentContextHelpers from "../lib/agentContextHelpers.js";
import type * as lib_agentMemoryCore from "../lib/agentMemoryCore.js";
import type * as lib_agentMetadata from "../lib/agentMetadata.js";
import type * as lib_agentOpsCore from "../lib/agentOpsCore.js";
import type * as lib_agentOpsHelpers from "../lib/agentOpsHelpers.js";
import type * as lib_agentOpsReadModelHelpers from "../lib/agentOpsReadModelHelpers.js";
import type * as lib_agentThreadContextCore from "../lib/agentThreadContextCore.js";
import type * as lib_agentThreadTargetSelectionHelpers from "../lib/agentThreadTargetSelectionHelpers.js";
import type * as lib_ai from "../lib/ai.js";
import type * as lib_analyticsCore from "../lib/analyticsCore.js";
import type * as lib_autoPlanCore from "../lib/autoPlanCore.js";
import type * as lib_autoPlanGroundingCacheCore from "../lib/autoPlanGroundingCacheCore.js";
import type * as lib_contactDiscoveryCore from "../lib/contactDiscoveryCore.js";
import type * as lib_deleteWorkspaceCascade from "../lib/deleteWorkspaceCascade.js";
import type * as lib_discoveryEdgesCore from "../lib/discoveryEdgesCore.js";
import type * as lib_disqualificationOutreachCore from "../lib/disqualificationOutreachCore.js";
import type * as lib_embeddingModels from "../lib/embeddingModels.js";
import type * as lib_enrichmentCore from "../lib/enrichmentCore.js";
import type * as lib_enrichmentPool from "../lib/enrichmentPool.js";
import type * as lib_errorHelpers from "../lib/errorHelpers.js";
import type * as lib_exaApiBudget from "../lib/exaApiBudget.js";
import type * as lib_functionBuilders from "../lib/functionBuilders.js";
import type * as lib_learningCore from "../lib/learningCore.js";
import type * as lib_linkdapiBudget from "../lib/linkdapiBudget.js";
import type * as lib_linkedinSearchHelpers from "../lib/linkedinSearchHelpers.js";
import type * as lib_logHelpers from "../lib/logHelpers.js";
import type * as lib_mediaCapabilityCore from "../lib/mediaCapabilityCore.js";
import type * as lib_memoryCore from "../lib/memoryCore.js";
import type * as lib_memoryEvaluationPool from "../lib/memoryEvaluationPool.js";
import type * as lib_memoryEvaluatorCore from "../lib/memoryEvaluatorCore.js";
import type * as lib_memoryHelpers from "../lib/memoryHelpers.js";
import type * as lib_modelTelemetry from "../lib/modelTelemetry.js";
import type * as lib_notificationHelpers from "../lib/notificationHelpers.js";
import type * as lib_onboardingNavigation from "../lib/onboardingNavigation.js";
import type * as lib_outreachCore from "../lib/outreachCore.js";
import type * as lib_outreachModelRoutingCore from "../lib/outreachModelRoutingCore.js";
import type * as lib_outreachPlanPool from "../lib/outreachPlanPool.js";
import type * as lib_outreachProgressHelpers from "../lib/outreachProgressHelpers.js";
import type * as lib_outreachRecoveryCore from "../lib/outreachRecoveryCore.js";
import type * as lib_patchHelpers from "../lib/patchHelpers.js";
import type * as lib_planBatchCore from "../lib/planBatchCore.js";
import type * as lib_planConstants from "../lib/planConstants.js";
import type * as lib_planCore from "../lib/planCore.js";
import type * as lib_planCycleUtils from "../lib/planCycleUtils.js";
import type * as lib_planHelpers from "../lib/planHelpers.js";
import type * as lib_planQualifiedUsageCore from "../lib/planQualifiedUsageCore.js";
import type * as lib_planUsageState from "../lib/planUsageState.js";
import type * as lib_preferredShellContext from "../lib/preferredShellContext.js";
import type * as lib_previewBatchLimits from "../lib/previewBatchLimits.js";
import type * as lib_previewEnrichmentPool from "../lib/previewEnrichmentPool.js";
import type * as lib_previewQualificationPool from "../lib/previewQualificationPool.js";
import type * as lib_prospectAnalyticsCore from "../lib/prospectAnalyticsCore.js";
import type * as lib_prospectInteractionHistoryCore from "../lib/prospectInteractionHistoryCore.js";
import type * as lib_prospectListFeedUtils from "../lib/prospectListFeedUtils.js";
import type * as lib_prospectProfileContextCore from "../lib/prospectProfileContextCore.js";
import type * as lib_prospectProfileContextHelpers from "../lib/prospectProfileContextHelpers.js";
import type * as lib_prospectSearchMerge from "../lib/prospectSearchMerge.js";
import type * as lib_prospectSearchText from "../lib/prospectSearchText.js";
import type * as lib_prospectingHelpers from "../lib/prospectingHelpers.js";
import type * as lib_providerReliability from "../lib/providerReliability.js";
import type * as lib_publicSocialCore from "../lib/publicSocialCore.js";
import type * as lib_publicThreadXCore from "../lib/publicThreadXCore.js";
import type * as lib_qualificationAuditApplyCore from "../lib/qualificationAuditApplyCore.js";
import type * as lib_qualificationAuditCore from "../lib/qualificationAuditCore.js";
import type * as lib_qualificationCore from "../lib/qualificationCore.js";
import type * as lib_qualificationEvaluationCore from "../lib/qualificationEvaluationCore.js";
import type * as lib_qualificationEvidenceCore from "../lib/qualificationEvidenceCore.js";
import type * as lib_qualificationFailureCore from "../lib/qualificationFailureCore.js";
import type * as lib_qualificationPool from "../lib/qualificationPool.js";
import type * as lib_qualificationScoringCore from "../lib/qualificationScoringCore.js";
import type * as lib_ragIndexing from "../lib/ragIndexing.js";
import type * as lib_readModelHelpers from "../lib/readModelHelpers.js";
import type * as lib_readModelRolloutHelpers from "../lib/readModelRolloutHelpers.js";
import type * as lib_relationshipHelpers from "../lib/relationshipHelpers.js";
import type * as lib_researchCore from "../lib/researchCore.js";
import type * as lib_resumeOutreachAfterUnarchive from "../lib/resumeOutreachAfterUnarchive.js";
import type * as lib_retrier from "../lib/retrier.js";
import type * as lib_setupFlowCore from "../lib/setupFlowCore.js";
import type * as lib_setupGenerationCore from "../lib/setupGenerationCore.js";
import type * as lib_setupPreviewCore from "../lib/setupPreviewCore.js";
import type * as lib_setupSessionCore from "../lib/setupSessionCore.js";
import type * as lib_setupThreadHelpers from "../lib/setupThreadHelpers.js";
import type * as lib_setupUrlAnalysisCore from "../lib/setupUrlAnalysisCore.js";
import type * as lib_setupWorkflowEvents from "../lib/setupWorkflowEvents.js";
import type * as lib_socialApiBudget from "../lib/socialApiBudget.js";
import type * as lib_socialApiFetch from "../lib/socialApiFetch.js";
import type * as lib_socialApiTwitterMap from "../lib/socialApiTwitterMap.js";
import type * as lib_styleDistillation from "../lib/styleDistillation.js";
import type * as lib_styleSourceCore from "../lib/styleSourceCore.js";
import type * as lib_threadHistoryHelpers from "../lib/threadHistoryHelpers.js";
import type * as lib_triggers from "../lib/triggers.js";
import type * as lib_twitterActionCatalog from "../lib/twitterActionCatalog.js";
import type * as lib_twitterActionPolicy from "../lib/twitterActionPolicy.js";
import type * as lib_twitterProfileLinkResolver from "../lib/twitterProfileLinkResolver.js";
import type * as lib_twitterSearchResultCore from "../lib/twitterSearchResultCore.js";
import type * as lib_twitterViewerStateService from "../lib/twitterViewerStateService.js";
import type * as lib_typeGuards from "../lib/typeGuards.js";
import type * as lib_unipileClient from "../lib/unipileClient.js";
import type * as lib_usageDashboardCore from "../lib/usageDashboardCore.js";
import type * as lib_userPostSearchCore from "../lib/userPostSearchCore.js";
import type * as lib_userUtils from "../lib/userUtils.js";
import type * as lib_wideEventLogger from "../lib/wideEventLogger.js";
import type * as lib_workflow from "../lib/workflow.js";
import type * as lib_workflowSafeProspect from "../lib/workflowSafeProspect.js";
import type * as lib_workspaceActivity from "../lib/workspaceActivity.js";
import type * as lib_workspaceEntitlements from "../lib/workspaceEntitlements.js";
import type * as lib_workspaceIcpSignalsCore from "../lib/workspaceIcpSignalsCore.js";
import type * as lib_workspaceNameHelpers from "../lib/workspaceNameHelpers.js";
import type * as lib_workspaceSetup from "../lib/workspaceSetup.js";
import type * as lib_workspaceStyleProfileCore from "../lib/workspaceStyleProfileCore.js";
import type * as lib_workspaceSystem from "../lib/workspaceSystem.js";
import type * as lib_workspaceThreadHelpers from "../lib/workspaceThreadHelpers.js";
import type * as lib_xActivity from "../lib/xActivity.js";
import type * as lib_xConnectionStateCore from "../lib/xConnectionStateCore.js";
import type * as lib_xConversationDiscoveryCore from "../lib/xConversationDiscoveryCore.js";
import type * as lib_xDm from "../lib/xDm.js";
import type * as lib_xPostLimits from "../lib/xPostLimits.js";
import type * as lib_xScopes from "../lib/xScopes.js";
import type * as lib_xdkAuth from "../lib/xdkAuth.js";
import type * as lib_xdkClient from "../lib/xdkClient.js";
import type * as lib_xdkConstants from "../lib/xdkConstants.js";
import type * as lib_xdkCrypto from "../lib/xdkCrypto.js";
import type * as lib_xdkTwitterProvider from "../lib/xdkTwitterProvider.js";
import type * as linkdapiBudget from "../linkdapiBudget.js";
import type * as linkedin from "../linkedin.js";
import type * as linkedinEngagement from "../linkedinEngagement.js";
import type * as linkedinStore from "../linkedinStore.js";
import type * as mediaMentions from "../mediaMentions.js";
import type * as mediaUpload from "../mediaUpload.js";
import type * as mediaUploadMutations from "../mediaUploadMutations.js";
import type * as memory from "../memory.js";
import type * as migrations from "../migrations.js";
import type * as outreach from "../outreach.js";
import type * as outreachActions from "../outreachActions.js";
import type * as outreachRecovery from "../outreachRecovery.js";
import type * as planBatchActions from "../planBatchActions.js";
import type * as planBatches from "../planBatches.js";
import type * as planUsage from "../planUsage.js";
import type * as plans from "../plans.js";
import type * as platformConversations from "../platformConversations.js";
import type * as polar from "../polar.js";
import type * as promo from "../promo.js";
import type * as prospectListFeed from "../prospectListFeed.js";
import type * as prospectMonitors from "../prospectMonitors.js";
import type * as prospectSearchUnified from "../prospectSearchUnified.js";
import type * as prospectSummaries from "../prospectSummaries.js";
import type * as prospectThreads from "../prospectThreads.js";
import type * as prospects from "../prospects.js";
import type * as providerReliability from "../providerReliability.js";
import type * as publicSocial from "../publicSocial.js";
import type * as readModels from "../readModels.js";
import type * as sendEmail from "../sendEmail.js";
import type * as setupSessions from "../setupSessions.js";
import type * as shell from "../shell.js";
import type * as socialActionExecutors from "../socialActionExecutors.js";
import type * as socialActions from "../socialActions.js";
import type * as socialApiBudget from "../socialApiBudget.js";
import type * as socialapi from "../socialapi.js";
import type * as socialapiMonitors from "../socialapiMonitors.js";
import type * as styleAnalysis from "../styleAnalysis.js";
import type * as styleAnalysisActions from "../styleAnalysisActions.js";
import type * as styleMonitorActions from "../styleMonitorActions.js";
import type * as styleMonitors from "../styleMonitors.js";
import type * as testerPlans from "../testerPlans.js";
import type * as twitterEngagement from "../twitterEngagement.js";
import type * as usage from "../usage.js";
import type * as users from "../users.js";
import type * as validators from "../validators.js";
import type * as waitlist from "../waitlist.js";
import type * as workflows_autoPlan from "../workflows/autoPlan.js";
import type * as workflows_autoPlanRecovery from "../workflows/autoPlanRecovery.js";
import type * as workflows_disqualificationOutreachCleanup from "../workflows/disqualificationOutreachCleanup.js";
import type * as workflows_enrichment from "../workflows/enrichment.js";
import type * as workflows_memory from "../workflows/memory.js";
import type * as workflows_outreach from "../workflows/outreach.js";
import type * as workflows_planBatch from "../workflows/planBatch.js";
import type * as workflows_preview from "../workflows/preview.js";
import type * as workflows_prospecting from "../workflows/prospecting.js";
import type * as workflows_qualification from "../workflows/qualification.js";
import type * as workflows_qualificationAudit from "../workflows/qualificationAudit.js";
import type * as workflows_qualificationAuditApplication from "../workflows/qualificationAuditApplication.js";
import type * as workflows_readModels from "../workflows/readModels.js";
import type * as workflows_setup from "../workflows/setup.js";
import type * as workspaceAgentOpsDaily from "../workspaceAgentOpsDaily.js";
import type * as workspaceAnalyticsDaily from "../workspaceAnalyticsDaily.js";
import type * as workspaceIcpSignals from "../workspaceIcpSignals.js";
import type * as workspaceQueryPerformanceDaily from "../workspaceQueryPerformanceDaily.js";
import type * as workspaceStats from "../workspaceStats.js";
import type * as workspaceStyleProfiles from "../workspaceStyleProfiles.js";
import type * as workspaceThreads from "../workspaceThreads.js";
import type * as workspaces from "../workspaces.js";
import type * as x from "../x.js";
import type * as xActivity from "../xActivity.js";
import type * as xConversationDiscovery from "../xConversationDiscovery.js";
import type * as xMutations from "../xMutations.js";
import type * as xPostLimits from "../xPostLimits.js";
import type * as xPostLimitsActions from "../xPostLimitsActions.js";
import type * as xStore from "../xStore.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  agentAttachments: typeof agentAttachments;
  agentOps: typeof agentOps;
  agentOpsReadModels: typeof agentOpsReadModels;
  agentTelemetry: typeof agentTelemetry;
  agentThreadContext: typeof agentThreadContext;
  "agents/index": typeof agents_index;
  "agents/internal": typeof agents_internal;
  "agents/outreach/context": typeof agents_outreach_context;
  "agents/outreach/index": typeof agents_outreach_index;
  "agents/outreach/rag": typeof agents_outreach_rag;
  "agents/outreach/tools/approveSocialActionRequest": typeof agents_outreach_tools_approveSocialActionRequest;
  "agents/outreach/tools/approveTask": typeof agents_outreach_tools_approveTask;
  "agents/outreach/tools/askHuman": typeof agents_outreach_tools_askHuman;
  "agents/outreach/tools/attachmentReferences": typeof agents_outreach_tools_attachmentReferences;
  "agents/outreach/tools/displayEntity": typeof agents_outreach_tools_displayEntity;
  "agents/outreach/tools/generatePlan": typeof agents_outreach_tools_generatePlan;
  "agents/outreach/tools/getProspectInteractionHistory": typeof agents_outreach_tools_getProspectInteractionHistory;
  "agents/outreach/tools/getProspectPlan": typeof agents_outreach_tools_getProspectPlan;
  "agents/outreach/tools/getSocialContext": typeof agents_outreach_tools_getSocialContext;
  "agents/outreach/tools/helpers": typeof agents_outreach_tools_helpers;
  "agents/outreach/tools/index": typeof agents_outreach_tools_index;
  "agents/outreach/tools/inspectWorkspace": typeof agents_outreach_tools_inspectWorkspace;
  "agents/outreach/tools/planLifecycle": typeof agents_outreach_tools_planLifecycle;
  "agents/outreach/tools/refinePlan": typeof agents_outreach_tools_refinePlan;
  "agents/outreach/tools/researchProspect": typeof agents_outreach_tools_researchProspect;
  "agents/outreach/tools/socialAction": typeof agents_outreach_tools_socialAction;
  "agents/outreach/tools/socialContextShared": typeof agents_outreach_tools_socialContextShared;
  "agents/outreach/tools/xPostLimitHelpers": typeof agents_outreach_tools_xPostLimitHelpers;
  "agents/prompts": typeof agents_prompts;
  "agents/tools/analyzeUrl": typeof agents_tools_analyzeUrl;
  "agents/tools/convertToSocialQueries": typeof agents_tools_convertToSocialQueries;
  "agents/tools/createWorkspace": typeof agents_tools_createWorkspace;
  "agents/tools/enrichProspect": typeof agents_tools_enrichProspect;
  "agents/tools/generateImprovedDescription": typeof agents_tools_generateImprovedDescription;
  "agents/tools/getUserStatus": typeof agents_tools_getUserStatus;
  "agents/tools/index": typeof agents_tools_index;
  "agents/tools/logging": typeof agents_tools_logging;
  "agents/tools/planBatch": typeof agents_tools_planBatch;
  "agents/tools/qualifyProspect": typeof agents_tools_qualifyProspect;
  "agents/tools/queryWorkspace": typeof agents_tools_queryWorkspace;
  "agents/tools/rememberWorkspaceMemory": typeof agents_tools_rememberWorkspaceMemory;
  "agents/tools/schemas": typeof agents_tools_schemas;
  "agents/tools/searchProspects": typeof agents_tools_searchProspects;
  "agents/tools/searchWorkspaceMemories": typeof agents_tools_searchWorkspaceMemories;
  "agents/tools/updateWorkspace": typeof agents_tools_updateWorkspace;
  "agents/tools/workspaceMemoryHelpers": typeof agents_tools_workspaceMemoryHelpers;
  "agents/tools/workspaceSetupContext": typeof agents_tools_workspaceSetupContext;
  analytics: typeof analytics;
  archivedProspectPause: typeof archivedProspectPause;
  autoPlanActions: typeof autoPlanActions;
  autoPlanGroundingCache: typeof autoPlanGroundingCache;
  autoPlanRuns: typeof autoPlanRuns;
  autocomplete: typeof autocomplete;
  autocompleteControl: typeof autocompleteControl;
  billing: typeof billing;
  chat: typeof chat;
  crons: typeof crons;
  discoveryEdges: typeof discoveryEdges;
  evaluator: typeof evaluator;
  exaApiBudget: typeof exaApiBudget;
  http: typeof http;
  "integrations/bishopi": typeof integrations_bishopi;
  "integrations/linkedin/getCompany": typeof integrations_linkedin_getCompany;
  "integrations/linkedin/getPostComments": typeof integrations_linkedin_getPostComments;
  "integrations/linkedin/getProfile": typeof integrations_linkedin_getProfile;
  "integrations/linkedin/getProfilePosts": typeof integrations_linkedin_getProfilePosts;
  "integrations/linkedin/linkdapiClient": typeof integrations_linkedin_linkdapiClient;
  "integrations/linkedin/profileIdentity": typeof integrations_linkedin_profileIdentity;
  "integrations/linkedin/searchPeople": typeof integrations_linkedin_searchPeople;
  "integrations/linkedin/searchPosts": typeof integrations_linkedin_searchPosts;
  "integrations/linkedin/searchUserPosts": typeof integrations_linkedin_searchUserPosts;
  "integrations/twitter/getProfile": typeof integrations_twitter_getProfile;
  "integrations/twitter/getThread": typeof integrations_twitter_getThread;
  "integrations/twitter/searchPosts": typeof integrations_twitter_searchPosts;
  "integrations/twitter/searchUserPosts": typeof integrations_twitter_searchUserPosts;
  "integrations/twitter/similarProfiles": typeof integrations_twitter_similarProfiles;
  interactions: typeof interactions;
  interactionsActions: typeof interactionsActions;
  keywords: typeof keywords;
  "lib/accessHelpers": typeof lib_accessHelpers;
  "lib/agentAttachmentReferenceCore": typeof lib_agentAttachmentReferenceCore;
  "lib/agentContextHelpers": typeof lib_agentContextHelpers;
  "lib/agentMemoryCore": typeof lib_agentMemoryCore;
  "lib/agentMetadata": typeof lib_agentMetadata;
  "lib/agentOpsCore": typeof lib_agentOpsCore;
  "lib/agentOpsHelpers": typeof lib_agentOpsHelpers;
  "lib/agentOpsReadModelHelpers": typeof lib_agentOpsReadModelHelpers;
  "lib/agentThreadContextCore": typeof lib_agentThreadContextCore;
  "lib/agentThreadTargetSelectionHelpers": typeof lib_agentThreadTargetSelectionHelpers;
  "lib/ai": typeof lib_ai;
  "lib/analyticsCore": typeof lib_analyticsCore;
  "lib/autoPlanCore": typeof lib_autoPlanCore;
  "lib/autoPlanGroundingCacheCore": typeof lib_autoPlanGroundingCacheCore;
  "lib/contactDiscoveryCore": typeof lib_contactDiscoveryCore;
  "lib/deleteWorkspaceCascade": typeof lib_deleteWorkspaceCascade;
  "lib/discoveryEdgesCore": typeof lib_discoveryEdgesCore;
  "lib/disqualificationOutreachCore": typeof lib_disqualificationOutreachCore;
  "lib/embeddingModels": typeof lib_embeddingModels;
  "lib/enrichmentCore": typeof lib_enrichmentCore;
  "lib/enrichmentPool": typeof lib_enrichmentPool;
  "lib/errorHelpers": typeof lib_errorHelpers;
  "lib/exaApiBudget": typeof lib_exaApiBudget;
  "lib/functionBuilders": typeof lib_functionBuilders;
  "lib/learningCore": typeof lib_learningCore;
  "lib/linkdapiBudget": typeof lib_linkdapiBudget;
  "lib/linkedinSearchHelpers": typeof lib_linkedinSearchHelpers;
  "lib/logHelpers": typeof lib_logHelpers;
  "lib/mediaCapabilityCore": typeof lib_mediaCapabilityCore;
  "lib/memoryCore": typeof lib_memoryCore;
  "lib/memoryEvaluationPool": typeof lib_memoryEvaluationPool;
  "lib/memoryEvaluatorCore": typeof lib_memoryEvaluatorCore;
  "lib/memoryHelpers": typeof lib_memoryHelpers;
  "lib/modelTelemetry": typeof lib_modelTelemetry;
  "lib/notificationHelpers": typeof lib_notificationHelpers;
  "lib/onboardingNavigation": typeof lib_onboardingNavigation;
  "lib/outreachCore": typeof lib_outreachCore;
  "lib/outreachModelRoutingCore": typeof lib_outreachModelRoutingCore;
  "lib/outreachPlanPool": typeof lib_outreachPlanPool;
  "lib/outreachProgressHelpers": typeof lib_outreachProgressHelpers;
  "lib/outreachRecoveryCore": typeof lib_outreachRecoveryCore;
  "lib/patchHelpers": typeof lib_patchHelpers;
  "lib/planBatchCore": typeof lib_planBatchCore;
  "lib/planConstants": typeof lib_planConstants;
  "lib/planCore": typeof lib_planCore;
  "lib/planCycleUtils": typeof lib_planCycleUtils;
  "lib/planHelpers": typeof lib_planHelpers;
  "lib/planQualifiedUsageCore": typeof lib_planQualifiedUsageCore;
  "lib/planUsageState": typeof lib_planUsageState;
  "lib/preferredShellContext": typeof lib_preferredShellContext;
  "lib/previewBatchLimits": typeof lib_previewBatchLimits;
  "lib/previewEnrichmentPool": typeof lib_previewEnrichmentPool;
  "lib/previewQualificationPool": typeof lib_previewQualificationPool;
  "lib/prospectAnalyticsCore": typeof lib_prospectAnalyticsCore;
  "lib/prospectInteractionHistoryCore": typeof lib_prospectInteractionHistoryCore;
  "lib/prospectListFeedUtils": typeof lib_prospectListFeedUtils;
  "lib/prospectProfileContextCore": typeof lib_prospectProfileContextCore;
  "lib/prospectProfileContextHelpers": typeof lib_prospectProfileContextHelpers;
  "lib/prospectSearchMerge": typeof lib_prospectSearchMerge;
  "lib/prospectSearchText": typeof lib_prospectSearchText;
  "lib/prospectingHelpers": typeof lib_prospectingHelpers;
  "lib/providerReliability": typeof lib_providerReliability;
  "lib/publicSocialCore": typeof lib_publicSocialCore;
  "lib/publicThreadXCore": typeof lib_publicThreadXCore;
  "lib/qualificationAuditApplyCore": typeof lib_qualificationAuditApplyCore;
  "lib/qualificationAuditCore": typeof lib_qualificationAuditCore;
  "lib/qualificationCore": typeof lib_qualificationCore;
  "lib/qualificationEvaluationCore": typeof lib_qualificationEvaluationCore;
  "lib/qualificationEvidenceCore": typeof lib_qualificationEvidenceCore;
  "lib/qualificationFailureCore": typeof lib_qualificationFailureCore;
  "lib/qualificationPool": typeof lib_qualificationPool;
  "lib/qualificationScoringCore": typeof lib_qualificationScoringCore;
  "lib/ragIndexing": typeof lib_ragIndexing;
  "lib/readModelHelpers": typeof lib_readModelHelpers;
  "lib/readModelRolloutHelpers": typeof lib_readModelRolloutHelpers;
  "lib/relationshipHelpers": typeof lib_relationshipHelpers;
  "lib/researchCore": typeof lib_researchCore;
  "lib/resumeOutreachAfterUnarchive": typeof lib_resumeOutreachAfterUnarchive;
  "lib/retrier": typeof lib_retrier;
  "lib/setupFlowCore": typeof lib_setupFlowCore;
  "lib/setupGenerationCore": typeof lib_setupGenerationCore;
  "lib/setupPreviewCore": typeof lib_setupPreviewCore;
  "lib/setupSessionCore": typeof lib_setupSessionCore;
  "lib/setupThreadHelpers": typeof lib_setupThreadHelpers;
  "lib/setupUrlAnalysisCore": typeof lib_setupUrlAnalysisCore;
  "lib/setupWorkflowEvents": typeof lib_setupWorkflowEvents;
  "lib/socialApiBudget": typeof lib_socialApiBudget;
  "lib/socialApiFetch": typeof lib_socialApiFetch;
  "lib/socialApiTwitterMap": typeof lib_socialApiTwitterMap;
  "lib/styleDistillation": typeof lib_styleDistillation;
  "lib/styleSourceCore": typeof lib_styleSourceCore;
  "lib/threadHistoryHelpers": typeof lib_threadHistoryHelpers;
  "lib/triggers": typeof lib_triggers;
  "lib/twitterActionCatalog": typeof lib_twitterActionCatalog;
  "lib/twitterActionPolicy": typeof lib_twitterActionPolicy;
  "lib/twitterProfileLinkResolver": typeof lib_twitterProfileLinkResolver;
  "lib/twitterSearchResultCore": typeof lib_twitterSearchResultCore;
  "lib/twitterViewerStateService": typeof lib_twitterViewerStateService;
  "lib/typeGuards": typeof lib_typeGuards;
  "lib/unipileClient": typeof lib_unipileClient;
  "lib/usageDashboardCore": typeof lib_usageDashboardCore;
  "lib/userPostSearchCore": typeof lib_userPostSearchCore;
  "lib/userUtils": typeof lib_userUtils;
  "lib/wideEventLogger": typeof lib_wideEventLogger;
  "lib/workflow": typeof lib_workflow;
  "lib/workflowSafeProspect": typeof lib_workflowSafeProspect;
  "lib/workspaceActivity": typeof lib_workspaceActivity;
  "lib/workspaceEntitlements": typeof lib_workspaceEntitlements;
  "lib/workspaceIcpSignalsCore": typeof lib_workspaceIcpSignalsCore;
  "lib/workspaceNameHelpers": typeof lib_workspaceNameHelpers;
  "lib/workspaceSetup": typeof lib_workspaceSetup;
  "lib/workspaceStyleProfileCore": typeof lib_workspaceStyleProfileCore;
  "lib/workspaceSystem": typeof lib_workspaceSystem;
  "lib/workspaceThreadHelpers": typeof lib_workspaceThreadHelpers;
  "lib/xActivity": typeof lib_xActivity;
  "lib/xConnectionStateCore": typeof lib_xConnectionStateCore;
  "lib/xConversationDiscoveryCore": typeof lib_xConversationDiscoveryCore;
  "lib/xDm": typeof lib_xDm;
  "lib/xPostLimits": typeof lib_xPostLimits;
  "lib/xScopes": typeof lib_xScopes;
  "lib/xdkAuth": typeof lib_xdkAuth;
  "lib/xdkClient": typeof lib_xdkClient;
  "lib/xdkConstants": typeof lib_xdkConstants;
  "lib/xdkCrypto": typeof lib_xdkCrypto;
  "lib/xdkTwitterProvider": typeof lib_xdkTwitterProvider;
  linkdapiBudget: typeof linkdapiBudget;
  linkedin: typeof linkedin;
  linkedinEngagement: typeof linkedinEngagement;
  linkedinStore: typeof linkedinStore;
  mediaMentions: typeof mediaMentions;
  mediaUpload: typeof mediaUpload;
  mediaUploadMutations: typeof mediaUploadMutations;
  memory: typeof memory;
  migrations: typeof migrations;
  outreach: typeof outreach;
  outreachActions: typeof outreachActions;
  outreachRecovery: typeof outreachRecovery;
  planBatchActions: typeof planBatchActions;
  planBatches: typeof planBatches;
  planUsage: typeof planUsage;
  plans: typeof plans;
  platformConversations: typeof platformConversations;
  polar: typeof polar;
  promo: typeof promo;
  prospectListFeed: typeof prospectListFeed;
  prospectMonitors: typeof prospectMonitors;
  prospectSearchUnified: typeof prospectSearchUnified;
  prospectSummaries: typeof prospectSummaries;
  prospectThreads: typeof prospectThreads;
  prospects: typeof prospects;
  providerReliability: typeof providerReliability;
  publicSocial: typeof publicSocial;
  readModels: typeof readModels;
  sendEmail: typeof sendEmail;
  setupSessions: typeof setupSessions;
  shell: typeof shell;
  socialActionExecutors: typeof socialActionExecutors;
  socialActions: typeof socialActions;
  socialApiBudget: typeof socialApiBudget;
  socialapi: typeof socialapi;
  socialapiMonitors: typeof socialapiMonitors;
  styleAnalysis: typeof styleAnalysis;
  styleAnalysisActions: typeof styleAnalysisActions;
  styleMonitorActions: typeof styleMonitorActions;
  styleMonitors: typeof styleMonitors;
  testerPlans: typeof testerPlans;
  twitterEngagement: typeof twitterEngagement;
  usage: typeof usage;
  users: typeof users;
  validators: typeof validators;
  waitlist: typeof waitlist;
  "workflows/autoPlan": typeof workflows_autoPlan;
  "workflows/autoPlanRecovery": typeof workflows_autoPlanRecovery;
  "workflows/disqualificationOutreachCleanup": typeof workflows_disqualificationOutreachCleanup;
  "workflows/enrichment": typeof workflows_enrichment;
  "workflows/memory": typeof workflows_memory;
  "workflows/outreach": typeof workflows_outreach;
  "workflows/planBatch": typeof workflows_planBatch;
  "workflows/preview": typeof workflows_preview;
  "workflows/prospecting": typeof workflows_prospecting;
  "workflows/qualification": typeof workflows_qualification;
  "workflows/qualificationAudit": typeof workflows_qualificationAudit;
  "workflows/qualificationAuditApplication": typeof workflows_qualificationAuditApplication;
  "workflows/readModels": typeof workflows_readModels;
  "workflows/setup": typeof workflows_setup;
  workspaceAgentOpsDaily: typeof workspaceAgentOpsDaily;
  workspaceAnalyticsDaily: typeof workspaceAnalyticsDaily;
  workspaceIcpSignals: typeof workspaceIcpSignals;
  workspaceQueryPerformanceDaily: typeof workspaceQueryPerformanceDaily;
  workspaceStats: typeof workspaceStats;
  workspaceStyleProfiles: typeof workspaceStyleProfiles;
  workspaceThreads: typeof workspaceThreads;
  workspaces: typeof workspaces;
  x: typeof x;
  xActivity: typeof xActivity;
  xConversationDiscovery: typeof xConversationDiscovery;
  xMutations: typeof xMutations;
  xPostLimits: typeof xPostLimits;
  xPostLimitsActions: typeof xPostLimitsActions;
  xStore: typeof xStore;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  actionRetrier: import("@convex-dev/action-retrier/_generated/component.js").ComponentApi<"actionRetrier">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  qualificationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"qualificationPool">;
  enrichmentPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"enrichmentPool">;
  previewQualificationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"previewQualificationPool">;
  previewEnrichmentPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"previewEnrichmentPool">;
  outreachPlanPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"outreachPlanPool">;
  memoryEvaluationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"memoryEvaluationPool">;
  rag: import("@convex-dev/rag/_generated/component.js").ComponentApi<"rag">;
  polar: import("@convex-dev/polar/_generated/component.js").ComponentApi<"polar">;
};
