/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as agentOps from "../agentOps.js";
import type * as agentTelemetry from "../agentTelemetry.js";
import type * as agents_index from "../agents/index.js";
import type * as agents_internal from "../agents/internal.js";
import type * as agents_outreach_index from "../agents/outreach/index.js";
import type * as agents_outreach_rag from "../agents/outreach/rag.js";
import type * as agents_outreach_tools_approveSocialActionRequest from "../agents/outreach/tools/approveSocialActionRequest.js";
import type * as agents_outreach_tools_approveTask from "../agents/outreach/tools/approveTask.js";
import type * as agents_outreach_tools_askHuman from "../agents/outreach/tools/askHuman.js";
import type * as agents_outreach_tools_displayEntity from "../agents/outreach/tools/displayEntity.js";
import type * as agents_outreach_tools_generatePlan from "../agents/outreach/tools/generatePlan.js";
import type * as agents_outreach_tools_getProspectPlan from "../agents/outreach/tools/getProspectPlan.js";
import type * as agents_outreach_tools_getSocialContext from "../agents/outreach/tools/getSocialContext.js";
import type * as agents_outreach_tools_helpers from "../agents/outreach/tools/helpers.js";
import type * as agents_outreach_tools_index from "../agents/outreach/tools/index.js";
import type * as agents_outreach_tools_refinePlan from "../agents/outreach/tools/refinePlan.js";
import type * as agents_outreach_tools_socialAction from "../agents/outreach/tools/socialAction.js";
import type * as agents_outreach_tools_socialContextShared from "../agents/outreach/tools/socialContextShared.js";
import type * as agents_outreach_tools_xPostLimitHelpers from "../agents/outreach/tools/xPostLimitHelpers.js";
import type * as agents_prompts from "../agents/prompts.js";
import type * as agents_tools_analyzeUrl from "../agents/tools/analyzeUrl.js";
import type * as agents_tools_convertToSocialQueries from "../agents/tools/convertToSocialQueries.js";
import type * as agents_tools_createWorkspace from "../agents/tools/createWorkspace.js";
import type * as agents_tools_enrichProspect from "../agents/tools/enrichProspect.js";
import type * as agents_tools_generateImprovedDescription from "../agents/tools/generateImprovedDescription.js";
import type * as agents_tools_getUserStatus from "../agents/tools/getUserStatus.js";
import type * as agents_tools_index from "../agents/tools/index.js";
import type * as agents_tools_qualifyProspect from "../agents/tools/qualifyProspect.js";
import type * as agents_tools_rememberWorkspaceMemory from "../agents/tools/rememberWorkspaceMemory.js";
import type * as agents_tools_schemas from "../agents/tools/schemas.js";
import type * as agents_tools_searchProspects from "../agents/tools/searchProspects.js";
import type * as agents_tools_searchWorkspaceMemories from "../agents/tools/searchWorkspaceMemories.js";
import type * as agents_tools_updateWorkspace from "../agents/tools/updateWorkspace.js";
import type * as agents_tools_workspaceMemoryHelpers from "../agents/tools/workspaceMemoryHelpers.js";
import type * as agents_tools_workspaceSetupContext from "../agents/tools/workspaceSetupContext.js";
import type * as analytics from "../analytics.js";
import type * as archivedProspectPause from "../archivedProspectPause.js";
import type * as autocomplete from "../autocomplete.js";
import type * as billing from "../billing.js";
import type * as chat from "../chat.js";
import type * as crons from "../crons.js";
import type * as discoveryEdges from "../discoveryEdges.js";
import type * as evaluator from "../evaluator.js";
import type * as http from "../http.js";
import type * as integrations_bishopi from "../integrations/bishopi.js";
import type * as integrations_linkedin_getCompany from "../integrations/linkedin/getCompany.js";
import type * as integrations_linkedin_getPostComments from "../integrations/linkedin/getPostComments.js";
import type * as integrations_linkedin_getProfile from "../integrations/linkedin/getProfile.js";
import type * as integrations_linkedin_getProfilePosts from "../integrations/linkedin/getProfilePosts.js";
import type * as integrations_linkedin_linkdapiClient from "../integrations/linkedin/linkdapiClient.js";
import type * as integrations_linkedin_profileIdentity from "../integrations/linkedin/profileIdentity.js";
import type * as integrations_linkedin_searchPeople from "../integrations/linkedin/searchPeople.js";
import type * as integrations_linkedin_searchPosts from "../integrations/linkedin/searchPosts.js";
import type * as integrations_linkedin_searchUserPosts from "../integrations/linkedin/searchUserPosts.js";
import type * as integrations_twitter_getProfile from "../integrations/twitter/getProfile.js";
import type * as integrations_twitter_getThread from "../integrations/twitter/getThread.js";
import type * as integrations_twitter_searchPosts from "../integrations/twitter/searchPosts.js";
import type * as integrations_twitter_searchUserPosts from "../integrations/twitter/searchUserPosts.js";
import type * as interactions from "../interactions.js";
import type * as interactionsActions from "../interactionsActions.js";
import type * as keywords from "../keywords.js";
import type * as lib_accessHelpers from "../lib/accessHelpers.js";
import type * as lib_agentMemoryCore from "../lib/agentMemoryCore.js";
import type * as lib_agentMetadata from "../lib/agentMetadata.js";
import type * as lib_agentOpsCore from "../lib/agentOpsCore.js";
import type * as lib_ai from "../lib/ai.js";
import type * as lib_analyticsCore from "../lib/analyticsCore.js";
import type * as lib_deleteWorkspaceCascade from "../lib/deleteWorkspaceCascade.js";
import type * as lib_discoveryEdgesCore from "../lib/discoveryEdgesCore.js";
import type * as lib_enrichmentCore from "../lib/enrichmentCore.js";
import type * as lib_enrichmentPool from "../lib/enrichmentPool.js";
import type * as lib_functionBuilders from "../lib/functionBuilders.js";
import type * as lib_learningCore from "../lib/learningCore.js";
import type * as lib_linkdapiBudget from "../lib/linkdapiBudget.js";
import type * as lib_logHelpers from "../lib/logHelpers.js";
import type * as lib_memoryCore from "../lib/memoryCore.js";
import type * as lib_memoryEvaluationPool from "../lib/memoryEvaluationPool.js";
import type * as lib_memoryEvaluatorCore from "../lib/memoryEvaluatorCore.js";
import type * as lib_memoryHelpers from "../lib/memoryHelpers.js";
import type * as lib_modelTelemetry from "../lib/modelTelemetry.js";
import type * as lib_notificationHelpers from "../lib/notificationHelpers.js";
import type * as lib_onboardingNavigation from "../lib/onboardingNavigation.js";
import type * as lib_outreachCore from "../lib/outreachCore.js";
import type * as lib_outreachPlanPool from "../lib/outreachPlanPool.js";
import type * as lib_patchHelpers from "../lib/patchHelpers.js";
import type * as lib_planConstants from "../lib/planConstants.js";
import type * as lib_planCore from "../lib/planCore.js";
import type * as lib_planCycleUtils from "../lib/planCycleUtils.js";
import type * as lib_planHelpers from "../lib/planHelpers.js";
import type * as lib_planUsageState from "../lib/planUsageState.js";
import type * as lib_preferredShellContext from "../lib/preferredShellContext.js";
import type * as lib_previewBatchLimits from "../lib/previewBatchLimits.js";
import type * as lib_previewEnrichmentPool from "../lib/previewEnrichmentPool.js";
import type * as lib_previewQualificationPool from "../lib/previewQualificationPool.js";
import type * as lib_prospectListFeedUtils from "../lib/prospectListFeedUtils.js";
import type * as lib_prospectSearchMerge from "../lib/prospectSearchMerge.js";
import type * as lib_prospectSearchText from "../lib/prospectSearchText.js";
import type * as lib_prospectingHelpers from "../lib/prospectingHelpers.js";
import type * as lib_qualificationCore from "../lib/qualificationCore.js";
import type * as lib_qualificationPool from "../lib/qualificationPool.js";
import type * as lib_ragIndexing from "../lib/ragIndexing.js";
import type * as lib_readModelHelpers from "../lib/readModelHelpers.js";
import type * as lib_readModelRolloutHelpers from "../lib/readModelRolloutHelpers.js";
import type * as lib_relationshipHelpers from "../lib/relationshipHelpers.js";
import type * as lib_resumeOutreachAfterUnarchive from "../lib/resumeOutreachAfterUnarchive.js";
import type * as lib_retrier from "../lib/retrier.js";
import type * as lib_setupFlowCore from "../lib/setupFlowCore.js";
import type * as lib_setupSessionCore from "../lib/setupSessionCore.js";
import type * as lib_setupThreadHelpers from "../lib/setupThreadHelpers.js";
import type * as lib_setupWorkflowEvents from "../lib/setupWorkflowEvents.js";
import type * as lib_socialApiBudget from "../lib/socialApiBudget.js";
import type * as lib_socialApiTwitterMap from "../lib/socialApiTwitterMap.js";
import type * as lib_styleDistillation from "../lib/styleDistillation.js";
import type * as lib_styleSourceCore from "../lib/styleSourceCore.js";
import type * as lib_triggers from "../lib/triggers.js";
import type * as lib_twitterActionCatalog from "../lib/twitterActionCatalog.js";
import type * as lib_twitterActionPolicy from "../lib/twitterActionPolicy.js";
import type * as lib_twitterViewerStateService from "../lib/twitterViewerStateService.js";
import type * as lib_typeGuards from "../lib/typeGuards.js";
import type * as lib_unipileClient from "../lib/unipileClient.js";
import type * as lib_userUtils from "../lib/userUtils.js";
import type * as lib_workflow from "../lib/workflow.js";
import type * as lib_workflowSafeProspect from "../lib/workflowSafeProspect.js";
import type * as lib_workspaceActivity from "../lib/workspaceActivity.js";
import type * as lib_workspaceEntitlements from "../lib/workspaceEntitlements.js";
import type * as lib_workspaceNameHelpers from "../lib/workspaceNameHelpers.js";
import type * as lib_workspaceSetup from "../lib/workspaceSetup.js";
import type * as lib_workspaceSystem from "../lib/workspaceSystem.js";
import type * as lib_xActivity from "../lib/xActivity.js";
import type * as lib_xConversationDiscoveryCore from "../lib/xConversationDiscoveryCore.js";
import type * as lib_xDm from "../lib/xDm.js";
import type * as lib_xPostLimits from "../lib/xPostLimits.js";
import type * as lib_xdkAuth from "../lib/xdkAuth.js";
import type * as lib_xdkClient from "../lib/xdkClient.js";
import type * as lib_xdkConstants from "../lib/xdkConstants.js";
import type * as lib_xdkCrypto from "../lib/xdkCrypto.js";
import type * as lib_xdkTwitterProvider from "../lib/xdkTwitterProvider.js";
import type * as linkdapiBudget from "../linkdapiBudget.js";
import type * as linkedin from "../linkedin.js";
import type * as linkedinStore from "../linkedinStore.js";
import type * as mediaUpload from "../mediaUpload.js";
import type * as mediaUploadMutations from "../mediaUploadMutations.js";
import type * as memory from "../memory.js";
import type * as outreach from "../outreach.js";
import type * as outreachActions from "../outreachActions.js";
import type * as planUsage from "../planUsage.js";
import type * as plans from "../plans.js";
import type * as platformConversations from "../platformConversations.js";
import type * as polar from "../polar.js";
import type * as promo from "../promo.js";
import type * as prospectListFeed from "../prospectListFeed.js";
import type * as prospectMonitors from "../prospectMonitors.js";
import type * as prospectSearchUnified from "../prospectSearchUnified.js";
import type * as prospectSummaries from "../prospectSummaries.js";
import type * as prospectThreads from "../prospectThreads.js";
import type * as prospects from "../prospects.js";
import type * as readModels from "../readModels.js";
import type * as sendEmail from "../sendEmail.js";
import type * as setupSessions from "../setupSessions.js";
import type * as shell from "../shell.js";
import type * as socialActionExecutors from "../socialActionExecutors.js";
import type * as socialActions from "../socialActions.js";
import type * as socialApiBudget from "../socialApiBudget.js";
import type * as socialapi from "../socialapi.js";
import type * as socialapiMonitors from "../socialapiMonitors.js";
import type * as socialapiMutations from "../socialapiMutations.js";
import type * as styleAnalysis from "../styleAnalysis.js";
import type * as styleAnalysisActions from "../styleAnalysisActions.js";
import type * as styleMonitorActions from "../styleMonitorActions.js";
import type * as styleMonitors from "../styleMonitors.js";
import type * as twitterEngagement from "../twitterEngagement.js";
import type * as users from "../users.js";
import type * as validators from "../validators.js";
import type * as waitlist from "../waitlist.js";
import type * as workflows_enrichment from "../workflows/enrichment.js";
import type * as workflows_memory from "../workflows/memory.js";
import type * as workflows_outreach from "../workflows/outreach.js";
import type * as workflows_preview from "../workflows/preview.js";
import type * as workflows_prospecting from "../workflows/prospecting.js";
import type * as workflows_qualification from "../workflows/qualification.js";
import type * as workflows_readModels from "../workflows/readModels.js";
import type * as workflows_setup from "../workflows/setup.js";
import type * as workspaceAnalyticsDaily from "../workspaceAnalyticsDaily.js";
import type * as workspaceStats from "../workspaceStats.js";
import type * as workspaceStyleProfiles from "../workspaceStyleProfiles.js";
import type * as workspaces from "../workspaces.js";
import type * as x from "../x.js";
import type * as xActivity from "../xActivity.js";
import type * as xConversationDiscovery from "../xConversationDiscovery.js";
import type * as xMutations from "../xMutations.js";
import type * as xPostLimits from "../xPostLimits.js";
import type * as xStore from "../xStore.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  agentOps: typeof agentOps;
  agentTelemetry: typeof agentTelemetry;
  "agents/index": typeof agents_index;
  "agents/internal": typeof agents_internal;
  "agents/outreach/index": typeof agents_outreach_index;
  "agents/outreach/rag": typeof agents_outreach_rag;
  "agents/outreach/tools/approveSocialActionRequest": typeof agents_outreach_tools_approveSocialActionRequest;
  "agents/outreach/tools/approveTask": typeof agents_outreach_tools_approveTask;
  "agents/outreach/tools/askHuman": typeof agents_outreach_tools_askHuman;
  "agents/outreach/tools/displayEntity": typeof agents_outreach_tools_displayEntity;
  "agents/outreach/tools/generatePlan": typeof agents_outreach_tools_generatePlan;
  "agents/outreach/tools/getProspectPlan": typeof agents_outreach_tools_getProspectPlan;
  "agents/outreach/tools/getSocialContext": typeof agents_outreach_tools_getSocialContext;
  "agents/outreach/tools/helpers": typeof agents_outreach_tools_helpers;
  "agents/outreach/tools/index": typeof agents_outreach_tools_index;
  "agents/outreach/tools/refinePlan": typeof agents_outreach_tools_refinePlan;
  "agents/outreach/tools/socialAction": typeof agents_outreach_tools_socialAction;
  "agents/outreach/tools/socialContextShared": typeof agents_outreach_tools_socialContextShared;
  "agents/outreach/tools/xPostLimitHelpers": typeof agents_outreach_tools_xPostLimitHelpers;
  "agents/prompts": typeof agents_prompts;
  "agents/tools/analyzeUrl": typeof agents_tools_analyzeUrl;
  "agents/tools/convertToSocialQueries": typeof agents_tools_convertToSocialQueries;
  "agents/tools/createWorkspace": typeof agents_tools_createWorkspace;
  "agents/tools/enrichProspect": typeof agents_tools_enrichProspect;
  "agents/tools/generateImprovedDescription": typeof agents_tools_generateImprovedDescription;
  "agents/tools/getUserStatus": typeof agents_tools_getUserStatus;
  "agents/tools/index": typeof agents_tools_index;
  "agents/tools/qualifyProspect": typeof agents_tools_qualifyProspect;
  "agents/tools/rememberWorkspaceMemory": typeof agents_tools_rememberWorkspaceMemory;
  "agents/tools/schemas": typeof agents_tools_schemas;
  "agents/tools/searchProspects": typeof agents_tools_searchProspects;
  "agents/tools/searchWorkspaceMemories": typeof agents_tools_searchWorkspaceMemories;
  "agents/tools/updateWorkspace": typeof agents_tools_updateWorkspace;
  "agents/tools/workspaceMemoryHelpers": typeof agents_tools_workspaceMemoryHelpers;
  "agents/tools/workspaceSetupContext": typeof agents_tools_workspaceSetupContext;
  analytics: typeof analytics;
  archivedProspectPause: typeof archivedProspectPause;
  autocomplete: typeof autocomplete;
  billing: typeof billing;
  chat: typeof chat;
  crons: typeof crons;
  discoveryEdges: typeof discoveryEdges;
  evaluator: typeof evaluator;
  http: typeof http;
  "integrations/bishopi": typeof integrations_bishopi;
  "integrations/linkedin/getCompany": typeof integrations_linkedin_getCompany;
  "integrations/linkedin/getPostComments": typeof integrations_linkedin_getPostComments;
  "integrations/linkedin/getProfile": typeof integrations_linkedin_getProfile;
  "integrations/linkedin/getProfilePosts": typeof integrations_linkedin_getProfilePosts;
  "integrations/linkedin/linkdapiClient": typeof integrations_linkedin_linkdapiClient;
  "integrations/linkedin/profileIdentity": typeof integrations_linkedin_profileIdentity;
  "integrations/linkedin/searchPeople": typeof integrations_linkedin_searchPeople;
  "integrations/linkedin/searchPosts": typeof integrations_linkedin_searchPosts;
  "integrations/linkedin/searchUserPosts": typeof integrations_linkedin_searchUserPosts;
  "integrations/twitter/getProfile": typeof integrations_twitter_getProfile;
  "integrations/twitter/getThread": typeof integrations_twitter_getThread;
  "integrations/twitter/searchPosts": typeof integrations_twitter_searchPosts;
  "integrations/twitter/searchUserPosts": typeof integrations_twitter_searchUserPosts;
  interactions: typeof interactions;
  interactionsActions: typeof interactionsActions;
  keywords: typeof keywords;
  "lib/accessHelpers": typeof lib_accessHelpers;
  "lib/agentMemoryCore": typeof lib_agentMemoryCore;
  "lib/agentMetadata": typeof lib_agentMetadata;
  "lib/agentOpsCore": typeof lib_agentOpsCore;
  "lib/ai": typeof lib_ai;
  "lib/analyticsCore": typeof lib_analyticsCore;
  "lib/deleteWorkspaceCascade": typeof lib_deleteWorkspaceCascade;
  "lib/discoveryEdgesCore": typeof lib_discoveryEdgesCore;
  "lib/enrichmentCore": typeof lib_enrichmentCore;
  "lib/enrichmentPool": typeof lib_enrichmentPool;
  "lib/functionBuilders": typeof lib_functionBuilders;
  "lib/learningCore": typeof lib_learningCore;
  "lib/linkdapiBudget": typeof lib_linkdapiBudget;
  "lib/logHelpers": typeof lib_logHelpers;
  "lib/memoryCore": typeof lib_memoryCore;
  "lib/memoryEvaluationPool": typeof lib_memoryEvaluationPool;
  "lib/memoryEvaluatorCore": typeof lib_memoryEvaluatorCore;
  "lib/memoryHelpers": typeof lib_memoryHelpers;
  "lib/modelTelemetry": typeof lib_modelTelemetry;
  "lib/notificationHelpers": typeof lib_notificationHelpers;
  "lib/onboardingNavigation": typeof lib_onboardingNavigation;
  "lib/outreachCore": typeof lib_outreachCore;
  "lib/outreachPlanPool": typeof lib_outreachPlanPool;
  "lib/patchHelpers": typeof lib_patchHelpers;
  "lib/planConstants": typeof lib_planConstants;
  "lib/planCore": typeof lib_planCore;
  "lib/planCycleUtils": typeof lib_planCycleUtils;
  "lib/planHelpers": typeof lib_planHelpers;
  "lib/planUsageState": typeof lib_planUsageState;
  "lib/preferredShellContext": typeof lib_preferredShellContext;
  "lib/previewBatchLimits": typeof lib_previewBatchLimits;
  "lib/previewEnrichmentPool": typeof lib_previewEnrichmentPool;
  "lib/previewQualificationPool": typeof lib_previewQualificationPool;
  "lib/prospectListFeedUtils": typeof lib_prospectListFeedUtils;
  "lib/prospectSearchMerge": typeof lib_prospectSearchMerge;
  "lib/prospectSearchText": typeof lib_prospectSearchText;
  "lib/prospectingHelpers": typeof lib_prospectingHelpers;
  "lib/qualificationCore": typeof lib_qualificationCore;
  "lib/qualificationPool": typeof lib_qualificationPool;
  "lib/ragIndexing": typeof lib_ragIndexing;
  "lib/readModelHelpers": typeof lib_readModelHelpers;
  "lib/readModelRolloutHelpers": typeof lib_readModelRolloutHelpers;
  "lib/relationshipHelpers": typeof lib_relationshipHelpers;
  "lib/resumeOutreachAfterUnarchive": typeof lib_resumeOutreachAfterUnarchive;
  "lib/retrier": typeof lib_retrier;
  "lib/setupFlowCore": typeof lib_setupFlowCore;
  "lib/setupSessionCore": typeof lib_setupSessionCore;
  "lib/setupThreadHelpers": typeof lib_setupThreadHelpers;
  "lib/setupWorkflowEvents": typeof lib_setupWorkflowEvents;
  "lib/socialApiBudget": typeof lib_socialApiBudget;
  "lib/socialApiTwitterMap": typeof lib_socialApiTwitterMap;
  "lib/styleDistillation": typeof lib_styleDistillation;
  "lib/styleSourceCore": typeof lib_styleSourceCore;
  "lib/triggers": typeof lib_triggers;
  "lib/twitterActionCatalog": typeof lib_twitterActionCatalog;
  "lib/twitterActionPolicy": typeof lib_twitterActionPolicy;
  "lib/twitterViewerStateService": typeof lib_twitterViewerStateService;
  "lib/typeGuards": typeof lib_typeGuards;
  "lib/unipileClient": typeof lib_unipileClient;
  "lib/userUtils": typeof lib_userUtils;
  "lib/workflow": typeof lib_workflow;
  "lib/workflowSafeProspect": typeof lib_workflowSafeProspect;
  "lib/workspaceActivity": typeof lib_workspaceActivity;
  "lib/workspaceEntitlements": typeof lib_workspaceEntitlements;
  "lib/workspaceNameHelpers": typeof lib_workspaceNameHelpers;
  "lib/workspaceSetup": typeof lib_workspaceSetup;
  "lib/workspaceSystem": typeof lib_workspaceSystem;
  "lib/xActivity": typeof lib_xActivity;
  "lib/xConversationDiscoveryCore": typeof lib_xConversationDiscoveryCore;
  "lib/xDm": typeof lib_xDm;
  "lib/xPostLimits": typeof lib_xPostLimits;
  "lib/xdkAuth": typeof lib_xdkAuth;
  "lib/xdkClient": typeof lib_xdkClient;
  "lib/xdkConstants": typeof lib_xdkConstants;
  "lib/xdkCrypto": typeof lib_xdkCrypto;
  "lib/xdkTwitterProvider": typeof lib_xdkTwitterProvider;
  linkdapiBudget: typeof linkdapiBudget;
  linkedin: typeof linkedin;
  linkedinStore: typeof linkedinStore;
  mediaUpload: typeof mediaUpload;
  mediaUploadMutations: typeof mediaUploadMutations;
  memory: typeof memory;
  outreach: typeof outreach;
  outreachActions: typeof outreachActions;
  planUsage: typeof planUsage;
  plans: typeof plans;
  platformConversations: typeof platformConversations;
  polar: typeof polar;
  promo: typeof promo;
  prospectListFeed: typeof prospectListFeed;
  prospectMonitors: typeof prospectMonitors;
  prospectSearchUnified: typeof prospectSearchUnified;
  prospectSummaries: typeof prospectSummaries;
  prospectThreads: typeof prospectThreads;
  prospects: typeof prospects;
  readModels: typeof readModels;
  sendEmail: typeof sendEmail;
  setupSessions: typeof setupSessions;
  shell: typeof shell;
  socialActionExecutors: typeof socialActionExecutors;
  socialActions: typeof socialActions;
  socialApiBudget: typeof socialApiBudget;
  socialapi: typeof socialapi;
  socialapiMonitors: typeof socialapiMonitors;
  socialapiMutations: typeof socialapiMutations;
  styleAnalysis: typeof styleAnalysis;
  styleAnalysisActions: typeof styleAnalysisActions;
  styleMonitorActions: typeof styleMonitorActions;
  styleMonitors: typeof styleMonitors;
  twitterEngagement: typeof twitterEngagement;
  users: typeof users;
  validators: typeof validators;
  waitlist: typeof waitlist;
  "workflows/enrichment": typeof workflows_enrichment;
  "workflows/memory": typeof workflows_memory;
  "workflows/outreach": typeof workflows_outreach;
  "workflows/preview": typeof workflows_preview;
  "workflows/prospecting": typeof workflows_prospecting;
  "workflows/qualification": typeof workflows_qualification;
  "workflows/readModels": typeof workflows_readModels;
  "workflows/setup": typeof workflows_setup;
  workspaceAnalyticsDaily: typeof workspaceAnalyticsDaily;
  workspaceStats: typeof workspaceStats;
  workspaceStyleProfiles: typeof workspaceStyleProfiles;
  workspaces: typeof workspaces;
  x: typeof x;
  xActivity: typeof xActivity;
  xConversationDiscovery: typeof xConversationDiscovery;
  xMutations: typeof xMutations;
  xPostLimits: typeof xPostLimits;
  xStore: typeof xStore;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  actionRetrier: import("@convex-dev/action-retrier/_generated/component.js").ComponentApi<"actionRetrier">;
  qualificationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"qualificationPool">;
  enrichmentPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"enrichmentPool">;
  previewQualificationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"previewQualificationPool">;
  previewEnrichmentPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"previewEnrichmentPool">;
  outreachPlanPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"outreachPlanPool">;
  memoryEvaluationPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"memoryEvaluationPool">;
  rag: import("@convex-dev/rag/_generated/component.js").ComponentApi<"rag">;
  polar: import("@convex-dev/polar/_generated/component.js").ComponentApi<"polar">;
};
